### ISSUE TITLE
Staking from contract's purse causes `ApiError::AuctionError(InvalidContext)` error.

### ISSUE THREAD

**Issue by zie1ony** [casper-network/casper-node#4999] opened 2024-12-03 10:38 UTC
### Category

Bug/Issue

### Your email address

maciej@odra.dev

### Integration Project Name(Optional)

odra

### Casper Network

Devnet

### Node Functionality

Execution Engine

### Description

We have tested token delegation from contracts and it looks like it doesn't work as expected.

## TL;DR
Purse created in a contract still can't be used to delegate.

## Why current test passes
This feature is covered with the test named `should_support_contract_staking` in `execution_engine_testing/tests/src/test/system_contracts/auction/mod.rs`. Contract executed there is `smart_contracts/contracts/test/staking-stored/src/main.rs`.

In the `call` method, `staking_purse` is created and passed to the contract as named keys. Then `stake` entry point in `smart_contracts/contracts/test/staking/src/lib.rs` works just fine. Probably it works because that this purse is still known to the account that deploys the wasm because it was created in the `call` method. Using new purse created in the contract makes this test to fail.

## Expected behavior
What I expect from this mechanism is that a purse created by a contract can be used to delegate.
If I change the code of `stake` method to this, I'd expect it still works:

```rust
#[no_mangle]
fn stake() {
    let staking_purse = get_uref_with_user_errors(
        STAKING_PURSE,
        StakingError::MissingStakingPurse,
        StakingError::InvalidStakingPurse,
    );
    let validator: PublicKey = match runtime::try_get_named_arg(ARG_VALIDATOR) {
        Some(validator_public_key) => validator_public_key,
        None => revert(ApiError::User(StakingError::MissingValidator as u16)),
    };
    let amount: U512 = runtime::get_named_arg(ARG_AMOUNT);

    // New purse truly owned by the contract 
    let new_purse = system::create_purse();
    system::transfer_from_purse_to_purse(staking_purse, new_purse, amount, None)
        .unwrap_or_revert_with(ApiError::Transfer);
    
    let contract_hash = system::get_auction();
    let args = runtime_args! {
        auction::ARG_DELEGATOR_PURSE => new_purse.addr(), // <- Using new purse.
        auction::ARG_VALIDATOR => validator,
        auction::ARG_AMOUNT => amount,
    };
    runtime::call_contract::<U512>(contract_hash, auction::METHOD_DELEGATE, args);
}
```

Instead this causes:
```
ApiError::AuctionError(InvalidContext) [64526]
```

**Comment by mssteuer** [comment] 2024-12-03 14:35
@devendran-m let's get @EdHastingsCasperAssociation to look at this please

**Comment by devendran-m** [comment] 2024-12-03 16:37
It's been triaged. Seems plausible. Ed's looking into it.

**Comment by EdHastingsCasperAssociation** [comment] 2024-12-04 00:04
https://github.com/casper-network/casper-node/pull/5002

**Comment by EdHastingsCasperAssociation** [comment] 2024-12-04 03:04
Excellent bug report @zie1ony 

The problem was simple and subtle; the main issue was that the purse was being passed to the auction contract from the staking contract as a `URefAddr` arg instead of as a complete `URef` and thus was not getting picked up or verified by the extract uref's logic. A hack had been introduced in the original work to uplift auction usage with the caller's access which is why it would work if the initiating account also had a handle on the uref, but that's not actually correct behavior. So, I removed the hack and tweaked the logic to expect the staking purse to be passed as a full `URef` arg, which is the correct & intended behavior. This fixed the bug.

**Comment by zie1ony** [comment] 2024-12-04 09:48
Thanks for quick fix.
Going forward with the implementation of our staking solution we've discovered next issue.

Here is the code, that shows the issue: https://github.com/odradev/casper-node/commit/209d48572f37e1e12d00569f1ebd4f57086de8f8

It errors with:
```
ApiError::Mint(UnapprovedSpendingAmount) [65045],
```

The problem I see here is that `amount` argument in a deploy is required to operate on the purse that contract owns. Yet there should not be such a connection.

This scenario should be possible:

1. UserA deploys the contract.
2. UserB calls `initialize_purse` on the contract and it makes a new purse and stores it in the contract's named keys. 
3. UserC uses `deposit` entry point to move CSPR from its main purse to contract's purse. This one is via wasm, and it requires `amount` arg to unlock user's main purse.
4. UserD uses `make_delegation` entry point that makes the contract to delegate using contract's purse crated in second step. This call is normal contract call, without `amount` argument.

**Comment by EdHastingsCasperAssociation** [comment] 2024-12-04 12:44
> The problem I see here is that amount argument in a deploy is required to operate on the purse that contract owns. Yet there should not be such a connection.

Not sure why you think that. The "amount" argument is expected by transfer. Delegations (and add bid, etc) are at root transfers with extra book keeping.  

> 1. UserA deploys the contract.
> 2. UserB calls initialize_purse on the contract and it makes a new purse and stores it in the contract's named keys.

This part is purely in userland. If you want to design a smart contract that separates the installation of the contract by one user and defer initialization to a potential later interaction from that same user or a different user that's up to you. 

> 3. UserC uses deposit entry point to move CSPR from its main purse to contract's purse. This one is via wasm, and it requires amount arg to unlock user's main purse.

This is misstated. All "movement" of CSPR from any purse to any other purse is accomplished via `transfer`, which requires `source`, `target`, and `amount` values to be provided. 

In the special case that a transfer is initiated from the caller's `main_purse`, the spending limit is enforced. This was a community requested behavior added a few years ago to prevent main purse depletion via multiple transfers within the same deploy. 

> 4. UserD uses make_delegation entry point that makes the contract to delegate using contract's purse crated in second step. This call is normal contract call, without amount argument.

As mentioned above, delegate (and add bid, etc) is at root a transfer of some number of CSPR (`amount`) from a specified purse that the caller has permissions on (`source`) to a bonding purse (`target`). The rest is just record keeping and rule enforcement. So, I don't understand why you think that should work _"without amount argument"_?


I'm open to further discussion, but this issue is for the reported bug. If there is some other bug around what you are talking about here it should go into a different bug issue so that the fix for this bug can merge and this issue can be closed. 

If there is no additional bug (i.e. it is working as intended) but we come to some agreement of a change in the existing function or the addition of new alternate functionality to support what you are trying to do then similarly that would also go into a different feature / capability issue.

**Comment by EdHastingsCasperAssociation** [comment] 2024-12-04 13:03
Tangentially, I would expect the typical flow for contract staking would be more like:

Initiator deposits some amount from some purse they have sufficient access for to the staking contract (under the hood, this is a transfer from the purse specified by the initiator to a purse controlled by the staking contract). 

_Side note: personally, I would never pass a main_purse with WRITE access to any other party as that amounts to granting them permanent access to it which is foolish. I would create a separate purse that I controlled, transfer token to that, and pass that purse to the staking purse. Another way that it could be accomplished is via an interaction with the staking contract to call an entrypoint that returned a URef with only ADD permissions that I'm expected to deposit into and then call a second entrypoint which would check to determine if the deposit occurred into that purse and if so do the rest of the work otherwise revert. But such considerations are userland / caveat emptor and not protocol / host determined or enforced_

Staking contract delegates that amount to a single validator or spreads it across multiple validators (under the hood, this is one or more calls to `delegate` which in turn further under the hood is ultimately a transfer from the specified staking contract controlled purse to the bonding purse associated with the specified validator).

Staking contract writes one or more book keeping records to keep track of the initiator, the relevant amount(s), and whatever else it needs to keep track of to manage its responsibilities.

**Closed as completed** 2024-12-04 22:58 UTC

**Comment by zie1ony** [comment] 2024-12-05 09:05
Fine :) You are right. The original bug issue was resolved and this can be closed. I'll work on a test case, that will show the issue I see to show what prevents me from implementing a staking contract the way I want it to work... or I'll prove myself it can be done the other way.

**Comment by devendran-m** [comment] 2024-12-05 10:38
Hi @zie1ony ,
Thank you very much. We will wait for your test results and if the issue that you are alluding to persists, we can create a separate issue for that.

**Comment by EdHastingsCasperAssociation** [comment] 2024-12-05 17:05
Discussed w/ Igor and we looked into the amount spending limit scenario. We've made a tweak, PR will be up shortly.

**Comment by devendran-m** [comment] 2024-12-18 07:03
Removed the "bug" tag based on the clarification from Ed;

> There was no bug per se, but in a particular edge case the `max_spending_amount` rule was being enforced. On discussion, we agreed that the edge case should be possible, and altered the code slightly to allow it to go through as a quality of life improvement. 

To paraphrase Ed's clarification;

> It would be better stated as Don't Enforce Spending Limit on Contract Staking
