### ISSUE TITLE
Network (all nodes) stalled during `network_soundness.py` test

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4031] opened 2023-06-07 21:52 UTC
When run locally on a rather decent PC, network was progressing until block 250 and then slowed down and stalled. Consensus noticed that and started to extend round lenghts (on some nodes even up to "32s 768ms").
Please note that for this test, the `network_soundness.py` was modified to NOT randomly start and stop nodes in an effort to reduce the potential pain points.
Unfortunately, no memory consumption report is available from this run.
https://files.slack.com/files-pri/TDVFB45LG-F05BDKZQ7LM/download/all-nodes-stall-no-restarting-just-joiners-with-huge-deploy.zip?origin_team=TDVFB45LG

**Comment by alsrdn** [comment] 2023-06-16 15:34
This issue was seen before [this PR](https://github.com/casper-network/casper-node/pull/4041) was merged.
With the old behaviour it’s still the case that consensus is active after switching to KeepUp though the cause of the forward synchronizer stall is different:
- while node 1 was still in Validate, it enqueued a block for execution (height 238, era 30)
- before the block could get marked complete, the node switches to KeepUp (probably because the accumulator had seen a newer block)
- the KeepUp logic sees block 237 as local tip and tries to synchronize block 238 using the forward builder in order to keep up
- meanwhile block 238 gets marked complete
- then the fwd synchronizer enqueues the block again (through the normal sync flow) and eventually gets stuck waiting for the block to get marked complete (which never happens since the block is already complete).

This would not happen with the new version of the code (post the PR referenced above) since now the node is not that eager to jump out of Validate. It will only do so if the accumulator tells it to Leap and will switch to CatchUp. Before it used to drop out of Validate to KeepUp if it seen even a single block difference.
So this particular issue would not be reproducible in the same way with the new version of the code:
- If a block is in flight to be marked complete when we switch to CatchUp, then CatchUp will leap
- Leaping will provide a block that is close to the tip, which should be much newer than the one that is in flight to be marked complete
- Synchronizing would start for the new block
- The old block would be marked complete
- CatchUp would switch to KeepUp
- KeepUp would see that the available block range includes the old block so it would not attempt to sync it
- Even if the mark complete is delayed so much that the old block gets marked complete after the node switched to KeepUp, the block would be considered historical and will not need re-execution anyway

Closing this ticket as this issue was solved by https://github.com/casper-network/casper-node/pull/4041

**Closed as completed by alsrdn** 2023-06-16 15:34 UTC
Labels: bug, triage
