### ISSUE TITLE
Extract casper-node:types to separate crate

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3722] opened 2023-02-28 16:24 UTC
Will require a mob session to identify the list to move.

**Comment by RitaMAllenCA** [comment] 2023-03-10 21:27
@piotr-dziubecki is this a duplicate of #3741?

**Comment by dwerner** [comment] 2023-04-11 14:50
> @piotr-dziubecki is this a duplicate of #3741?

No, EE types are also needing to be extracted, but this is the node's internal types.

**Comment by alsrdn** [comment] 2023-06-13 16:05
After discussing with @Fraser999 it seems like the likely candidates for moving are `Deploy` and `Block` for which there are already other tickets open.
Currently investigating if it's feasible to have types that are JSON encoded into a separate crate and separated from the domain types.

**Comment by alsrdn** [comment] 2023-06-19 15:40
Moving JSON encoded types to a new crate will need to be properly discussed, planned and specced into separate ticket(s). Since this ticket was not specifically about that work, closing this for now.

**Closed as not planned by alsrdn** 2023-06-19 15:40 UTC
