### ISSUE TITLE
Revisit the MainReactor::switch_block_header field

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3852] opened 2023-04-14 18:27 UTC
This field was initially intended to be a cache of the most recent switch block (initially set to None, and once set to Some it should stay Some). At some point, we added code that sets it back to None, which is probably incorrect. We need to revisit this code, possibly removing the switch_block_header field and replacing it with a call to storage. This also requires checking if all places that rely on this field do so correctly

**Comment by rafal-ch** [comment] 2023-04-19 13:25
Commits of interest:

The field was introduced [here](https://github.com/casper-network/casper-node/commit/7f975f5fc9f1eff98ba5dad3b5b4acd38924decc) and was used to keep track of **immediate** switch blocks. Since day 1 we had the logic of setting it to `None`.

Pretty much next day it was modified [here](https://github.com/casper-network/casper-node/commit/c985bc755e95d73d5e999bea5105fde07c045147). The field was renamed to `switch_block`, but the logic of setting it to `None` is still in place, albeit modified (`ReactorState::Validate` is now also checking if this field is `None`).

**Comment by rafal-ch** [comment] 2023-04-19 13:41
The "sync to ttl" function was first added [here](https://github.com/casper-network/casper-node/commit/320440aac74c7583b001a5e0ee3a806df6307eac) and it was **not** using the `switch_block` field. It relied on data from storage.

It got broken [here](https://github.com/casper-network/casper-node/commit/8f529c0c1851ab584a573a28fd999af637b1e604), as a result of incorrect implementation of [this](https://github.com/casper-network/casper-node/pull/3428#discussion_r1039622653) comment and remain unnoticed for ~4 months until [this](https://github.com/casper-network/casper-node/pull/3813/commits/54668801c3c27cc9b48073bef2bccb6058ad4656) fix was provided.

**Comment by rafal-ch** [comment] 2023-04-19 14:00
Currently, the `switch_block_header == None` is used to:
1. indicate that we might [possibly be at genesis](https://github.com/casper-network/casper-node/blob/dev/node/src/reactor/main_reactor/catch_up.rs#L132-L135)
2. [detect](https://github.com/casper-network/casper-node/blob/dev/node/src/reactor/main_reactor/control.rs#L467) if we should commit upgrade and [abort](https://github.com/casper-network/casper-node/blob/dev/node/src/reactor/main_reactor/control.rs#L114) node if we're committing upgrade [without](https://github.com/casper-network/casper-node/blob/dev/node/src/reactor/main_reactor/control.rs#L394) a switch block
3. abort processing of `validate_instruction` and, as [this comment](https://github.com/casper-network/casper-node/blob/dev/node/src/reactor/main_reactor/validate.rs#L37) suggests, the `switch_block` member of the `MainReactor` was intended to be occasionally set to `None`.

**Comment by rafal-ch** [comment] 2023-04-19 14:13
In an effort to fix [#3597](https://github.com/casper-network/casper-node/issues/3597), we changed the decision on when to set this field to `None` via this [PR](https://github.com/casper-network/casper-node/pull/3610).

However, even earlier we've been [altering the logic](https://github.com/casper-network/casper-node/commit/e70a836f70a16c5c9508184aa6ebafddfb6418a5#diff-ea02e6cf88dd93f39b659e8772c87219d3f5ebb962a0c6833cbb1baac90d80e6R1036-R1056) _(link requires the "Load diff" button to be pressed on `main_reactor.rs`)_ and relying on the local tip height to determine if we should update the value.

**Conclusion:**
I suggest leaving the `MainReactor::switch_block_header` as is and closing this ticket. Refactoring it out right now may be risky because I'm not sure if the required behavior is covered by tests (be it UTs, nightlies or SRE).

cc: @Fraser999 @EdHastingsCasperLabs

**Comment by rafal-ch** [comment] 2023-04-25 15:31
@EdHastingsCasperLabs says - let's do it.

**Closed as completed** 2023-05-31 13:08 UTC
