### ISSUE TITLE
Add metrics to the "fast sync" process

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2642] opened 2022-02-02 19:08 UTC

**Comment by rafal-ch** [comment] 2022-02-18 13:10
@piotr-dziubecki which ticket this one is considered to be the duplicate of? https://github.com/casper-network/casper-node/issues/2010?
I'd like to add a link to PR to an appropriate ticket.

**Closed as completed** 2022-12-05 14:36 UTC
Labels: Epic
