### ISSUE TITLE
Genesis validator node stalled during `network_soundness.py` test

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4032] opened 2023-06-07 22:00 UTC
When run locally on a rather decent PC, node-4 got stuck at block 656. It is aware of the next block, it has enough sigs and is stored, deploy buffer is notified. Actually, it is aware of a huge amount of more recent blocks, up until 3522 when the test ended.
Node never executes further blocks (`Validate: should_validate queue_depth 5`)
Please note that for this test, the `network_soundness.py` was modified to NOT randomly start and stop nodes in an effort to reduce the potential pain points. Additionally, to eliminate the impact of huge execution result on a network with short block times (NCTL), the test was also modified to NOT send big deploys to the network.

https://files.slack.com/files-pri/TDVFB45LG-F05C6AK0WV6/download/graph_2__1_.svg?origin_team=TDVFB45LG
https://files.slack.com/files-pri/TDVFB45LG-F05BGFKGS1Z/download/node-4-stuck-no-huge-deploys-no-restarts.zip?origin_team=TDVFB45LG

**Comment by alsrdn** [comment] 2023-06-19 15:36
This issue happened before we merged [this PR](https://github.com/casper-network/casper-node/pull/4041). In the old version of the code consensus was able to enqueue blocks for execution while the node was in CatchUp.
This happened here as well, blocks were enqueued and executed while the node was in CatchUp. The node does not expect this to happen and once the node switched out of CatchUp the shared execution pre-state was updated to block 652 because block 651 was the latest complete block.
After this happened, some in-flight marked complete operations for blocks 652-655 finished. The next block that would be enqueued for execution was 656 but since the execution pre-state was not updated the node remains stuck waiting for block 652.
CatchUp does and should not track block execution so it's not a problem that the execution pre-state was reset.
The problem is that the node switched out of Validate without deactivating the era in consensus.
This is fixed by: https://github.com/casper-network/casper-node/pull/4041

**Closed as completed by alsrdn** 2023-06-19 15:36 UTC
Labels: bug, triage
