### ISSUE TITLE
Do not warn about harmless dropped responders

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2207] opened 2021-10-12 13:55 UTC
A dropped Responder is like an asynchronous function call that never returned. It's a decision whether to handle failures here or not, currently we log potentially confusing error messages even in cases where the dropping is most without meaningful consequence. While from a component's perspective, changing reactors is a "crash" of everything around it, this usually is not an issue if the component itself is also shutdown or pending requests are not otherwise especially "valuable".
This ticket is for adding a "global" (per-reactor, not truly global) variable that indicates we are considering dropped responders harmless at the moment, for example while shutting down the reactor. It can be stored on the Runner or similar as an Arc<AtomicBool> with a clone to each created EffectBuilder. Once shutting down, we can set the flag, having it change how the running request tasks are handling dropped responders.

**Comment by Fraser999** [comment] 2021-10-27 11:33
Please triage #2240 while working on this ticket to investigate whether the node in question was shutting down or not.  If it was, please close #2240 as a duplicate of this ticket.  If not, leave a comment to that effect on that ticket, since we'll need to investigate it further.

The triage should be fairly quick - if that turns out to not be the case, please let me know.

**Closed as completed** 2021-11-11 19:43 UTC
Labels: node
