### ISSUE TITLE
Stalled node continues to run

### ISSUE THREAD

**Issue by Fraser999** [casper-network/casper-node#1498] opened 2021-05-26 16:01 UTC
The stalled node 2 in #1496 ran for 22 minutes in a stalled state (stuck at the switch block immediately before the upgrade).  I was expecting that after being stalled for 10 minutes that consensus would trigger a shutdown.

(Related: #1501)

**Comment by afck** [comment] 2021-05-31 10:26
In principle the standstill alert works. I set
```toml
maximum_round_exponent = 12
```
in the chainspec, so the maximum round length would be 4 seconds. A node counts as offline after being silent for [three maximum-length rounds](https://github.com/casper-network/casper-node/blob/a2d6511d17aa7df75a633542d207c280a775248e/node/src/components/consensus/highway_core/state.rs#L55), i.e. after 12 seconds in this test.

I also set
```toml
standstill_timeout = "1min"
```
in the config of node 1.

I then started the network, stopped nodes 2 and 3, and restarted node 1:
```
$ nctl-start
$ nctl-stop node=2
$ nctl-stop node=3

$ nctl-view-chain-lfb
2021-05-31T11:59:01.402070 [INFO] [51782] NCTL :: last finalized block hash @ node-1 = f2556c54efa4216882157b8359e911ca137c21efbfa87f2f8c8c9cedd59ed1cd
2021-05-31T11:59:01.497436 [INFO] [51782] NCTL :: last finalized block hash @ node-2 = 'N/A'
2021-05-31T11:59:01.554904 [INFO] [51782] NCTL :: last finalized block hash @ node-3 = 'N/A'
2021-05-31T11:59:01.644949 [INFO] [51782] NCTL :: last finalized block hash @ node-4 = f2556c54efa4216882157b8359e911ca137c21efbfa87f2f8c8c9cedd59ed1cd
2021-05-31T11:59:01.800020 [INFO] [51782] NCTL :: last finalized block hash @ node-5 = f2556c54efa4216882157b8359e911ca137c21efbfa87f2f8c8c9cedd59ed1cd
2021-05-31T11:59:01.884051 [INFO] [51782] NCTL :: last finalized block hash @ node-6 = 'N/A'
2021-05-31T11:59:02.019905 [INFO] [51782] NCTL :: last finalized block hash @ node-7 = 'N/A'
2021-05-31T11:59:02.075080 [INFO] [51782] NCTL :: last finalized block hash @ node-8 = 'N/A'
2021-05-31T11:59:02.136490 [INFO] [51782] NCTL :: last finalized block hash @ node-9 = 'N/A'
2021-05-31T11:59:02.193554 [INFO] [51782] NCTL :: last finalized block hash @ node-10 = 'N/A'

$ nctl-restart node=1 hash=f2556c54efa4216882157b8359e911ca137c21efbfa87f2f8c8c9cedd59ed1cd
```

As expected:
* Once nodes 2 and 3 were offline, nodes 1, 4 and 5 realized that no quorum was online and stopped creating new units.
* After its restart, node 1 waited for 1 minute. Since no new units were coming in it requested the latest state.
* After one more minute it was happy: `progress detected`. Because it had requested and received the first few units of the era from nodes 2 and 3.
* Another minute passed and it was unhappy again: `no progress`. It had synced the protocol state but not new units were being produced anymore because too much weight was offline to finalize anything. It raised the standstill alert and shut down.

```json
{"timestamp":"May 31 11:59:38.713","level":"INFO","fields":{"message":"no progress in the last 1m, creating latest state request","instance_id":"fc7de4c239ea9286cf60fcb1769c4867763f2bf5a96a0601394c1ef3cd325e9a"},"target":"casper_node::components::consensus::protocols::highway","span":{"ev":267,"name":"dispatch events"},"spans":[{"ev":267,"name":"crank"},{"ev":267,"name":"dispatch events"}]}

{"timestamp":"May 31 12:00:38.713","level":"DEBUG","fields":{"message":"progress detected; scheduling next standstill check in 1m","instance_id":"fc7de4c239ea9286cf60fcb1769c4867763f2bf5a96a0601394c1ef3cd325e9a"},"target":"casper_node::components::consensus::protocols::highway","span":{"ev":777,"name":"dispatch events"},"spans":[{"ev":777,"name":"crank"},{"ev":777,"name":"dispatch events"}]}

{"timestamp":"May 31 12:01:38.713","level":"INFO","fields":{"message":"no progress in the last 1m, raising standstill alert","instance_id":"fc7de4c239ea9286cf60fcb1769c4867763f2bf5a96a0601394c1ef3cd325e9a"},"target":"casper_node::components::consensus::protocols::highway","span":{"ev":1021,"name":"dispatch events"},"spans":[{"ev":1021,"name":"crank"},{"ev":1021,"name":"dispatch events"}]}

{"timestamp":"May 31 12:01:38.713","level":"ERROR","fields":{"message":"fatal error via control announcement","file":"node/src/components/consensus/era_supervisor.rs","line":"1196","msg":"current era is stalled; please retry"},"target":"casper_node::reactor","span":{"ev":1022,"name":"dispatch events"},"spans":[{"ev":1022,"name":"crank"},{"ev":1022,"name":"dispatch events"}]}
```

So it takes surprisingly long for the standstill alert to trigger, especially for a restarting node, because:
* It takes three _maximum_ round lengths until the online nodes realize that too much state is offline, and stop adding to the protocol state.
* A joining node will _not_ shutdown after a single `standstill_timeout`: It will first request the protocol state and wait for another `standstill_timeout`. After that, if it received _any_ unit in the meantime, it will just reschedule the timer. Only after a third `standstill_timeout` it will raise the standstill alert and shut down.

However, if in #1496 the joining node really received no units, that still doesn't explain why it kept running for _22 minutes_. Unfortunately the problem is hard to reproduce and we didn't have the above logs yet.

**Comment by afck** [comment] 2021-06-04 14:07
Closing this, since we cannot reproduce it.

**Closed by afck** 2021-06-04 14:07 UTC
Labels: bug
