### ISSUE TITLE
Commit Many Execution Effects In A Single Pass For a Deploy

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1946] opened 2021-08-19 12:25 UTC

**Comment by MParlikar** [comment] 2021-09-17 15:34
From what I understand, this is an important optimization that should improve efficiency and throughput.  We should prioritize this @EdHastingsCasperLabs @piotr-dziubecki for 1.5

**Comment by dwerner** [comment] 2021-11-01 15:22
@EdHastingsCasperLabs correct me if I'm missing the nuance here, but it appears to me that this issue is in an IS-A relationship (ie, duplicate of) https://app.zenhub.com/workspaces/engineering-60953fafb1945f0011a3592d/issues/casper-network/casper-node/1945 , which has a PR up https://github.com/casper-network/casper-node/pull/2277

**Comment by xcthulhu** [comment] 2021-11-01 19:06
@dwerner this _might_ mean that we want to write all effects at once, rather than making many interstitial (and unreferenced) state roots as we write each effect at a time.

**Comment by dwerner** [comment] 2021-11-15 16:03
@cspramit  this is distinct from https://app.zenhub.com/workspaces/engineering-60953fafb1945f0011a3592d/issues/casper-network/casper-node/1945 , which has a PR up #2277 as I was asking about. So this should -not- be in review.

**Closed as completed** 2021-11-29 16:26 UTC
Labels: duplicate, execution engine
