### ISSUE TITLE
Outgoing `BlockAndDeploys` responses seem to not be captured in metrics properly.

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#3039] opened 2022-05-26 13:10 UTC
Outgoing messages' size and count is supposed to be captured in the `small_network` Metrics but our test indicate they're not (see screenshots).
![image](https://user-images.githubusercontent.com/29494759/170494002-ef0a597b-cb7b-4a04-8cf5-87b5157a19fc.png)

![image](https://user-images.githubusercontent.com/29494759/170494031-be4075a6-58ce-4c6d-b5b3-890c607926af.png)

**Comment by goral09** [comment] 2022-06-02 11:32
Closing - could not reproduce. It's possible that it was a glitch in reporting metrics. Will re-open if the issues repeats.

**Closed as completed** 2022-06-02 11:32 UTC
Labels: stretch goal
