### ISSUE TITLE
Investigate slowdown in large network test

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3973] opened 2023-05-19 14:15 UTC
Investigate the issues reported in [this thread](https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1684407375630229)

**Comment by rafal-ch** [comment] 2023-06-07 19:44
It looks like the slowdown has been reproduced again.
Details are in the internal discussion [here](https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1686127058296509).

We were initially planning to close this ticket with the summary of previous investigation, but seems like we need to dig a little bit more into this issue. We should probably be trying to connect directly to the network that exhibits the slowdown or try to reproduce in not locally with NCTL, but using Jenkins test environment.

cc: @RitaMAllenCA @alsrdn

**Comment by rafal-ch** [comment] 2023-06-09 09:50
It turns out that the original problem was not reproduced. Instead, a different one was uncovered (tracked here: https://github.com/casper-network/casper-node/issues/4037).

So we can close this one wit appropriate comment from @alsrdn , as originally planned.

cc: @RitaMAllenCA

**Comment by alsrdn** [comment] 2023-06-09 14:42
Closing this issue for now as it is not of concern.
Only a handful of validators lagged behind but not enough to slow down the network. Eventually the validators that were behind managed to get back up to date with one validator (v38) catching up by leaping. Investigation into the logs did not provide a definitive reason of why some of the validators slowed down. Some observations could be made when comparing comparing validator 172.142.100.74 (that was lagging behind) with 172.142.80.152 (validator that was operating normally):
- During the period of high rate of deploys 172.142.100.74 lagged behind causing its execution queue to grow. After the deploy burst finished it managed to execute all the blocks in the queue and get back in line with the others.
- Comparing the timestamps in the logs for 172.142.100.74 showed that generally it took it a bit longer to execute blocks (which in turn takes it longer to mark them complete) than in the case of 172.142.80.152. I’ve plotted the execution durations based on the logs (green is 172.142.100.74, blue is 172.142.80.152). This affected the nodes recovery when the queue length grew. The difference in execution time accumulated to over 45second more on 172.142.100.74 vs 172.142.80.152 over the period of the first 300 blocks. So the node was getting left behind even more while the queue_depth was greater than 1.
- The IO profiles of both nodes looked similar in the metrics so I don’t think it’s an IO issue.
- There is a difference in the time it took to receive the proposal for (presumably) block 222 and adding it as a valid proposal between the 2 nodes. On 172.142.80.152 this took 830 ms, on 172.142.100.74 this took 5487 ms.

**Closed as completed by alsrdn** 2023-06-09 14:42 UTC
Labels: bug
