### ISSUE TITLE
Nodes OOM after ~4h of soundness test

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4024] opened 2023-06-06 12:16 UTC
Long running soundness test caused the nodes to OOM, producing 1.4Gb of debug logs each. Tested on commit `78c58599596271e267890a23fb8ff5a91866a34a` with the test modified to:

1. not end after 0.5h (as it does normally)
2. allow nodes 6 minutes to sync (instead of 2, as normal)

No output from the console available, since system got unresponsive and I had to force-reboot.
Logs attached (luckily, they compress quite well).
https://files.slack.com/files-pri/TDVFB45LG-F05AYJN7CDU/download/logs_-_oom.zip?origin_team=TDVFB45LG

**Comment by rafal-ch** [comment] 2023-06-12 14:20
@RitaMAllenCA 
I think we can close this one - the OOM fix [is merged](https://github.com/casper-network/casper-node/pull/4039).

Also, the huge log issue caused by logging full execution results [has been improved](https://github.com/casper-network/casper-node/pull/4019).

cc: @Fraser999

**Closed as completed** 2023-06-12 18:15 UTC
Labels: bug, release blocker
