### ISSUE TITLE
Implement factory pattern MVP

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4179] opened 2023-07-28 15:45 UTC

**Comment by rafal-ch** [comment] 2023-08-14 09:48
Is this a duplicate of https://github.com/casper-network/casper-node/issues/2064?

**Comment by RitaMAllenCA** [comment] 2023-08-22 14:24
That's the epic for the work - this is the story, so there is some overlap

**Closed as completed** 2023-09-05 14:51 UTC
