### ISSUE TITLE
Investigate failed swap_validator_set.sh test in nightly

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4095] opened 2023-06-29 14:23 UTC
Failed run: https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/8566/1/4

**Comment by alsrdn** [comment] 2023-07-06 13:06
Same issue as with https://github.com/casper-network/casper-node/issues/4070. Issue was with a node (node-3) that couldn’t switch from Validate to KeepUp when it was supposed to stop validating. This is because when it tries to switch to KeepUp the era was already deactivated by consensus. The fix is already merged https://github.com/casper-network/casper-node/pull/4075 so I will just close this ticket. This failed run was from before the fix was merged.

Closing this ticket because the issue is already fixed.

**Closed as completed by alsrdn** 2023-07-06 13:06 UTC
Labels: bug, triage
