### ISSUE TITLE
Investigate failed upgrade scenario 07 nightly test

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4033] opened 2023-06-08 20:01 UTC
Brief investigation of https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/8450/1/4 shows that node-3 successfully upgraded and ran in Validate mode until executing block c88c..cee1 at height 120.  At this point, it fell back from Validate to KeepUp, but the block synchronizer eventually became stuck repeatedly reporting need next: Nothing with 0 peers.  Eventually (after 3 mins) it switched to CatchUp and began to sync leap, but before this could be completed, the test deemed the node to have stalled and failed the test.

**Comment by georgepisaltu** [comment] 2023-06-22 08:49
The root cause of this problem was a combination of 2 factors:
- faulty behavior in `validate.rs` where a `BlockSync` instruction from the accumulator would kick the node into `KeepUp` mode, fixed in [this PR](https://github.com/casper-network/casper-node/pull/4041/files#diff-f17c86719f52aec37fe748dda08c43ec2ee5b9822ba52c0a56957033c4d3ecca) already.
- a race condition where the block was executed in validate mode and announced as a meta block (executed, not yet marked complete) and the accumulator emitted the effect to mark the block complete in storage, but `validate_instruction` was called before that could happen, leading to the behavior in the first bullet point.

From my point of view, this particular bug can be closed. However, I would note there is no mechanism of ensuring the block is marked complete in one swoop after being announced as meta block, so any existing or future logic relying on complete block semantics should be designed with this in mind.

**Closed as completed by georgepisaltu** 2023-06-22 08:49 UTC
Labels: bug, triage
