### ISSUE TITLE
 Make RPCs distinguish whether we have state for a root hash in feat-fast-sync.

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2302] opened 2021-11-04 16:17 UTC
If a client asks for some trie based on a block's root hash, the response should not look the same in these two cases:

* We don't have the full state for that block.
* We do have the full state and we know that that entry does not exist.

We should also add a new RPC so we can ask a node what is the oldest block that it has fully stored (including body, deploys and state).

Reporter: @afck

**Comment by Fraser999** [comment] 2022-03-17 13:43
Duplicate of https://github.com/casper-network/casper-node/issues/2632

**Closed as completed by Fraser999** 2022-03-17 13:43 UTC
Labels: duplicate, release blocker, node, fast-sync
