### ISSUE TITLE
Stabilize the 1.5 RC

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3444] opened 2022-12-06 14:16 UTC
fix incoming bugs, make all tests pass (including NCTL test suite)

**Comment by rafal-ch** [comment] 2022-12-06 15:05
Issues in progress:

- :heavy_check_mark: "early validator joiner" doesn't execute blocks - fixed

- :heavy_check_mark: update the NCTL's `setup_shared.sh` to handle the `validators` param of `global-state-update-gen` tool in order for the upgrade test to be able to progress - under review :eyes: 
https://github.com/casper-network/casper-node/pull/3451

- :heavy_check_mark: after upgrade nodes start in era=0 and don't progress - fixed by Fraser in https://github.com/casper-network/casper-node/pull/3472
 
- :heavy_check_mark: node 1.4.x shuts down for upgrade, then 1.5 is started. It commits upgrade, then it switches: `"CatchUp: switch to Upgrading"` and then panics in `casper_execution_engine::call_host_auction()` - in progress :eyes: 
-- _the root cause is the modified `auction_delay` in chainspec between 1.4.x and current feat-fast-sync-v2 - to be discussed on standup_
-- the decision is to keep things as is, since `auction_delay` was never meant to be changed from `1` - if it is set to `1` on both pre- and post-upgrade versions, nodes don't crash when doing calculations on the snapshot. We might improve handling of the changes, but not for 1.5

- :heavy_check_mark: how to handle upgrades when `era_duration` changes? currently we're banning peers because they send SyncLeap that we consider incorrect (too many trusted ancestor headers) - fixed in https://github.com/casper-network/casper-node/pull/3486

- :heavy_check_mark:  upgrade finishes correctly (as per `upgrade_scenario_01`) after the staged chainspec of `1.4.8` was updated to contain `auction_delay=1`. However, the final sanity checks fail since now we have some non-deterministic errors in logs (for example: "Historical: failed leap, remaining attempts: {}"). We can demote the non-det errors to warnings or come up with some smarter sanity checks.
Fixed in https://github.com/casper-network/casper-node/pull/3507

- :heavy_check_mark: - issue discoverd by SRE:
```
Update - 1/8 joiners have not yet joined after 5+ hours
"message":"peer rejected our request for a sync leap","peer":"tls:21f9..0687","sync_leap_identifier":"block hash 2827..8323 trusted_ancestor_only: false"
```
**Not an issue** - the tooling should be updated to provide a "fresh" trusted hash on restart

- :heavy_check_mark: - issue discoverd by SRE with upgrade tests:
2k+ errors in log: `tried to start fetching a sync leap without peers to ask`
every peer is probably banned because `sent handshake without chainspec hash`
Fixed in https://github.com/casper-network/casper-node/pull/3510

**Root cause:**
1) node runs in 1.0.0
2) upgrade is staged
3) node upgrades to 2.0.0
4) get_sync_leap responds with 1.0.0 (since such is the highest complete block in storage)
5) it commits the immediate switch block after the upgrade
6) and now correctly responds to sync_leaps (highest complete block in storage is 2.0.0)
Possible solution: do not respond to sync leaps when upgrading but switch block has not been created yet

- :heavy_check_mark: - unused block capacity in 1.5: "_seeing a range of 50% to 90% of block capacity unused_" - fixed in https://github.com/casper-network/casper-node/pull/3524

- :eyes: - emergency upgrade fails with `ShutdownForUpgrade: validator_weights cannot be missing`

**Closed as completed** 2023-01-03 15:18 UTC
