### ISSUE TITLE
Linear sync performance

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2206] opened 2021-10-12 13:53 UTC
Linear sync performance of blocks full of 2500 native transfers is worse than network speed.  Taking 130-200% of network tip speed.  This means that we produce up to two tip blocks before linear syncing a full historical block.  At 800 transfers we progress only about 2x tip speed.  Unless there are empty blocks to sync, we will never reach the tip.  So a fully-loaded network is not joinable.

Pls refer - https://casperlabs-team.slack.com/archives/C01ULKL8G8J/p1634225087228000
1.3.4 Branch used - https://github.com/casper-network/casper-node-private/tree/linear_sync_fix   << 

https://grafana.casperlabs.io/d/24t3s9Dnz/testnet-casper?orgId=1&from=now-30m&to=now&refresh=10s

**Comment by cspramit** [comment] 2021-10-14 15:57
@darthsiroftardis talk to @Fraser999  about adding metrics around switch-block , step-function et al fyi

**Comment by fraser** [comment] 2021-10-14 16:40
Hi @cspramit , I think you tagged the wrong `@fraser` :)

**Comment by Fraser999** [comment] 2021-10-19 10:48
This ticket is no longer deemed a release blocker, due to other performance gains realised recently.

This work should perhaps still be planned out and completed as aspects may be applicable to fast-sync, but it is not deemed a priority at the moment.

**Comment by goral09** [comment] 2021-11-15 16:40
We think that the performance issues observed during linear chain synchronization is not actually caused by inefficencies in the linear chain implementation but the slow IO on the receiving nodes (that the joining one is syncing with). Closing ticket ticket as there will be no work done in the `LinearChainSync` component.

**Closed as completed by goral09** 2021-11-15 16:40 UTC
Labels: node
